// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp9JcxZ6tQCP5bB-krZtVXaZJQg96Kvb4',
    appId: '1:645759938739:web:8b1e8ca96bbda9551cc0c6',
    messagingSenderId: '645759938739',
    projectId: 'flutter-update-7e8b5',
    authDomain: 'flutter-update-7e8b5.firebaseapp.com',
    databaseURL: 'https://flutter-update-7e8b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-update-7e8b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKSy_-SwWZXL9B-q8LgA3E1eaKb7RTI0g',
    appId: '1:645759938739:android:82e5075ca89d1cb61cc0c6',
    messagingSenderId: '645759938739',
    projectId: 'flutter-update-7e8b5',
    databaseURL: 'https://flutter-update-7e8b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-update-7e8b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVj8Mol1btrafhefVGUlShHUPMLz66rCs',
    appId: '1:645759938739:ios:8e3e3a8ad1eabf631cc0c6',
    messagingSenderId: '645759938739',
    projectId: 'flutter-update-7e8b5',
    databaseURL: 'https://flutter-update-7e8b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-update-7e8b5.appspot.com',
    iosClientId:
        '645759938739-41cohm1is4joafjcveao7bcptie6b82b.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshFruits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVj8Mol1btrafhefVGUlShHUPMLz66rCs',
    appId: '1:645759938739:ios:8e3e3a8ad1eabf631cc0c6',
    messagingSenderId: '645759938739',
    projectId: 'flutter-update-7e8b5',
    databaseURL: 'https://flutter-update-7e8b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-update-7e8b5.appspot.com',
    iosClientId:
        '645759938739-41cohm1is4joafjcveao7bcptie6b82b.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshFruits',
  );
}
